# Generated by Django 4.0.4 on 2022-04-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
